export const globalState = $state({
  isGLTFUploaded: false,
  gltfFile: "",
  blueprintPreview: "" as string,
  showComparison: false,
  currentMesh: "" as string | null,
  isFullScreen: false,
  isRendering: false,
  currentAsset: undefined,
  doors: {},
  stairs: {},
  windows: {},
  enemy: {},
  houses: {},
  dining: {},
  floorCount: 0,
});
