export const globalState = $state({
  isGLTFUploaded: false,
  gltfFile: "",
  blueprintPreview: "" as string,
  blueprintPreviews: [] as string[], // one entry per floor, for the stacked view left panel
  showComparison: false,
  showStackedView: false,
  stackedGltfFile: "" as string,
  currentMesh: "" as string | null,
  isFullScreen: false,
  isRendering: false,
  currentAsset: undefined,
  doors: {},
  stairs: {},
  windows: {},
  enemy: {},
  houses: {},
  dining: {},
  floorCount: 0,
  isChatOpen: false,
  chatMessages: [] as { role: "user" | "assistant"; content: string }[],
  groqApiKey: import.meta.env.VITE_GROQ_API_KEY || "",
});
