<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Author: Zian (https://sketchfab.com/zian_0912)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/door-d23ec435af454cf985292778dbd65c9e
Title: Door
-->

<script lang="ts">
  import { onMount } from "svelte";
  import { T } from "@threlte/core";
  import { TransformControls } from "@threlte/extras";
  import { globalState } from "$lib/state.svelte";
  let { id, doorGltf, ref = $bindable() } = $props();

  let helperAxesSize = $state(0);
  let controls: TransformControls | undefined = $state();
  onMount(() => {
    const updateCoords = () => {
      if (controls) {
        globalState.doors[id] = controls.worldPosition;
      }
    };
    controls?.addEventListener("change", updateCoords);

    return () => controls?.removeEventListener("change", updateCoords);
  });
</script>

<TransformControls
  bind:controls
  size={helperAxesSize}
  position.x={globalState.doors[id].x}
  position.y={globalState.doors[id].y}
  position.z={globalState.doors[id].z}
>
  {#if $doorGltf}
    <T
      bind:ref
      dispose={false}
      is={$doorGltf.scene.clone()}
      scale={0.1}
      onpointerenter={(e) => (helperAxesSize = 1)}
      onpointerleave={(e) => (helperAxesSize = 0)}
    />
  {/if}
</TransformControls>
