<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Author: wolfgar74 (https://sketchfab.com/wolfgar74)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-spiral-stairs-free-023fa16b631a461ba45d86ccbdc37e2a
Title: Wooden Spiral Stairs (Free)
-->

<script lang="ts">
  import { onMount } from "svelte";
  import { T } from "@threlte/core";
  import { TransformControls } from "@threlte/extras";
  import { globalState } from "$lib/state.svelte";
  let { id, houseGltf, ref = $bindable() } = $props();

  let helperAxesSize = $state(0);
  let controls: TransformControls | undefined = $state();
  onMount(() => {
    const updateCoords = () => {
      if (controls) {
        globalState.houses[id] = controls.worldPosition;
      }
    };
    controls?.addEventListener("change", updateCoords);

    return () => controls?.removeEventListener("change", updateCoords);
  });
</script>

<TransformControls
  bind:controls
  size={helperAxesSize}
  position.x={globalState.houses[id].x}
  position.y={globalState.houses[id].y}
  position.z={globalState.houses[id].z}
>
  {#if $houseGltf}
    <T
      bind:ref
      dispose={false}
      is={$houseGltf.scene.clone()}
      scale={0.15}
      onpointerenter={(e) => (helperAxesSize = 1)}
      onpointerleave={(e) => (helperAxesSize = 0)}
    />
  {/if}
</TransformControls>
