<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Author: jaggu (https://sketchfab.com/jagath.krishna)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/window-0624b680947d4ff38c5b8e60977f1fb6
Title: WINDOW
-->

<script lang="ts">
  import { onMount } from "svelte";
  import { T } from "@threlte/core";
  import { TransformControls } from "@threlte/extras";
  import { globalState } from "$lib/state.svelte";
  let { id, windowGltf, ref = $bindable() } = $props();

  let helperAxesSize = $state(0);
  let controls: TransformControls | undefined = $state();
  onMount(() => {
    const updateCoords = () => {
      if (controls) {
        globalState.windows[id] = controls.worldPosition;
      }
    };
    controls?.addEventListener("change", updateCoords);

    return () => controls?.removeEventListener("change", updateCoords);
  });
</script>

<TransformControls
  bind:controls
  size={helperAxesSize}
  position.x={globalState.windows[id].x}
  position.y={globalState.windows[id].y}
  position.z={globalState.windows[id].z}
>
  {#if $windowGltf}
    <T
      bind:ref
      dispose={false}
      is={$windowGltf.scene.clone()}
      scale={5}
      onpointerenter={(e) => (helperAxesSize = 0.7)}
      onpointerleave={(e) => (helperAxesSize = 0)}
    />
  {/if}
</TransformControls>
